"""
Actions Module — Multi-pass Transcription & Document Generation

Executes the agent's decided actions:
- Image preprocessing (brightness, contrast, sharpness)
- Multi-pass transcription via Gemini API
- Enhancement pass for quality improvement
- Word document generation with proper formatting
"""

import os
import google.generativeai as genai
from PIL import Image, ImageEnhance, ImageFilter
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
from dotenv import load_dotenv

load_dotenv()


def preprocess_image(image: Image.Image, recommendations: list) -> Image.Image:
    """
    Apply preprocessing based on perception recommendations.
    Returns the processed image ready for transcription.
    """
    processed = image.copy()

    for rec in recommendations:
        action = rec.get("action", "none")

        if action == "increase_brightness":
            enhancer = ImageEnhance.Brightness(processed)
            processed = enhancer.enhance(1.4)

        elif action == "decrease_brightness":
            enhancer = ImageEnhance.Brightness(processed)
            processed = enhancer.enhance(0.7)

        elif action == "enhance_contrast":
            enhancer = ImageEnhance.Contrast(processed)
            processed = enhancer.enhance(1.5)

        elif action == "sharpen_image":
            enhancer = ImageEnhance.Sharpness(processed)
            processed = enhancer.enhance(2.0)

        elif action == "upscale_image":
            # Upscale by 1.5x using LANCZOS
            w, h = processed.size
            new_size = (int(w * 1.5), int(h * 1.5))
            processed = processed.resize(new_size, Image.LANCZOS)

    # Always resize to max 1024 for API efficiency
    processed.thumbnail((1024, 1024))

    return processed


def transcribe_image(image: Image.Image, prompt: str) -> str:
    """
    Send image to Gemini API for transcription.
    Uses API key failover from environment variables.
    """
    keys = [os.getenv("GEMINI_KEY_1"), os.getenv("GEMINI_KEY_2"), os.getenv("GEMINI_KEY_3")]
    keys = [k for k in keys if k]

    if not keys:
        raise ValueError("No API keys found in environment variables!")

    last_error = ""
    for i, key in enumerate(keys):
        try:
            genai.configure(api_key=key)
            model = genai.GenerativeModel('gemini-2.5-flash-lite')
            response = model.generate_content([prompt, image])
            return response.text
        except Exception as e:
            last_error = str(e)
            if "429" in last_error:
                continue
            else:
                break

    raise RuntimeError(f"All API keys failed. Last error: {last_error}")


def enhance_transcription(original_text: str, enhancement_prompt: str) -> str:
    """
    Run an enhancement pass on existing transcription.
    Uses Gemini to refine and correct the text.
    """
    formatted_prompt = enhancement_prompt.format(text=original_text)

    keys = [os.getenv("GEMINI_KEY_1"), os.getenv("GEMINI_KEY_2"), os.getenv("GEMINI_KEY_3")]
    keys = [k for k in keys if k]

    if not keys:
        return original_text  # Fallback: return original if no keys

    for key in keys:
        try:
            genai.configure(api_key=key)
            model = genai.GenerativeModel('gemini-2.5-flash-lite')
            response = model.generate_content(formatted_prompt)
            return response.text
        except Exception:
            continue

    return original_text  # Fallback: return original if enhancement fails


def generate_word_document(text: str, metadata: dict = None) -> BytesIO:
    """
    Generate a professionally formatted Word document from transcribed text.
    Includes metadata, headers, and structured content.
    """
    doc = Document()

    # --- Document Styling ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    font.color.rgb = RGBColor(44, 44, 44)

    # --- Title ---
    title = doc.add_heading('Transcribed Notes', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(46, 46, 46)

    # --- Metadata block ---
    if metadata:
        meta_para = doc.add_paragraph()
        meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta_run = meta_para.add_run(
            f"Generated by Notes2Doc AI Agent | "
            f"Content Type: {metadata.get('content_type', 'Text')} | "
            f"Confidence: {metadata.get('confidence', 0):.0%}"
        )
        meta_run.font.size = Pt(9)
        meta_run.font.color.rgb = RGBColor(128, 128, 128)
        meta_run.font.italic = True

    doc.add_paragraph("")  # Spacer

    # --- Content ---
    lines = text.split('\n')
    for line in lines:
        stripped = line.strip()

        if not stripped:
            doc.add_paragraph("")
            continue

        # Detect headings (lines starting with # or ALL CAPS short lines)
        if stripped.startswith('# '):
            doc.add_heading(stripped.lstrip('# '), level=1)
        elif stripped.startswith('## '):
            doc.add_heading(stripped.lstrip('## '), level=2)
        elif stripped.startswith('### '):
            doc.add_heading(stripped.lstrip('### '), level=3)
        elif len(stripped) < 60 and stripped.isupper():
            doc.add_heading(stripped.title(), level=2)
        elif stripped.startswith('- ') or stripped.startswith('• '):
            # Bullet points
            para = doc.add_paragraph(stripped[2:], style='List Bullet')
        elif stripped.startswith('[Diagram:'):
            # Diagram descriptions — styled differently
            para = doc.add_paragraph()
            run = para.add_run(stripped)
            run.font.italic = True
            run.font.color.rgb = RGBColor(0, 102, 153)
        else:
            doc.add_paragraph(stripped)

    # --- Footer ---
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("— Generated by Notes2Doc Agentic System —")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(180, 180, 180)
    footer_run.font.italic = True

    # Save to BytesIO
    bio = BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio
